pipeline:
  name: jc-quantum-bank
  identifier: jcquantumbank
  projectIdentifier: jcproject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: jcgithubconnector
        repoName: quantum-bank
        build: <+input>
  stages:
    - stage:
        name: Build Test and Push
        identifier: Build_Test_and_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: true
            paths: []
          execution:
            steps:
              - parallel:
                  - step:
                      type: Owasp
                      name: Owasp
                      identifier: Owasp
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                  - step:
                      type: OsvScanner
                      name: OsvScanner
                      identifier: OsvScanner
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
              - step:
                  type: RunTests
                  name: RunTests
                  identifier: RunTests
                  spec:
                    language: Python
                    buildTool: Pytest
                    args: ./test/*.py --junitxml=out_report.xml
                    runOnlySelectedTests: true
                    preCommand: pip install -r requirements.txt
                    enableTestSplitting: false
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: jcdockerhubconnector
                    repo: john8260/quantum-bank-backend
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: ./Dockerfile
    - stage:
        name: Deploy to Kubernetes
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: quantum_bank_backend_service
            gitBranch: main
          environment:
            environmentRef: jcharnessenv
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: kubernetes
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: HarnessApproval
                  identifier: HarnessApproval
                  spec:
                    approvalMessage: Please review the following information and approve the deployment progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - _project_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
